// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzspwxijmczcgruhnqvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6c3B3eGlqbWN6Y2dydWhucXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mzg0MzQsImV4cCI6MjA2NzExNDQzNH0.DL7LC6CO9iRv6hS3wXipDjezGZ5fxGE5QI5GX0yDYis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});